[package]
name = "rvvc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.65.1"
dunce = "1.0.4"
fs_extra = "1.3.0"

[dependencies]
